[workspace]

members = [
  "06-conversion",
  "07-statement",
  "08-flow_control",
  "09-function",
  "10-mods",
#  "11-crates",
  "12-cargo",
  "13-attribute",
  "14-generics",
  "15-scope",
  "16-traits",
  "17-macros",
  "18-error_handling",
  "19-std_types",
  "20-std_misc",
]
