[package]
name = "tokio_task_tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
# tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "signal", "macros", "time"] }
tokio = { version = "1.43.0", features = ["full"]}
tokio-util = { version = "0.7.13", features = ["full"] }
